import { body, param, query } from 'express-validator';
import {
  ENROLLMENT_STATUSES,
  MAX_PAGE_SIZE,
  MAX_SEARCH_LENGTH,
  STUDENT_EMAIL_PATTERN,
  STUDENT_EDITABLE_FIELDS,
  STUDENT_PHONE_PATTERN,
  STUDENT_PROTECTED_FIELDS,
  STUDENT_SORT_DIRECTIONS,
  STUDENT_SORT_FIELDS,
  STUDENT_YEARS,
} from '../constants/student.js';

/**
 * Rules are declared as factories so the create and update chains each get
 * their own validator instances — reusing one instance and calling `.optional()`
 * on it would silently loosen the create rules too.
 */

const name = () =>
  body('name').trim().notEmpty().withMessage('Student name is required.')
    .bail().isLength({ min: 2, max: 120 })
    .withMessage('Student name must be between 2 and 120 characters.');

const email = () =>
  body('email').trim().notEmpty().withMessage('Email is required.')
    .bail().matches(STUDENT_EMAIL_PATTERN).withMessage('Please provide a valid email address.')
    .normalizeEmail();

const phone = () =>
  body('phone').trim().notEmpty().withMessage('Phone number is required.')
    .bail().matches(STUDENT_PHONE_PATTERN).withMessage('Please provide a valid phone number.');

const course = () =>
  body('course').trim().notEmpty().withMessage('Course is required.')
    .bail().isLength({ max: 120 }).withMessage('Course cannot exceed 120 characters.');

const year = () =>
  body('year').trim().notEmpty().withMessage('Year of study is required.')
    .bail().isIn(STUDENT_YEARS).withMessage(`Year must be one of: ${STUDENT_YEARS.join(', ')}.`);

const department = () =>
  body('department').trim().notEmpty().withMessage('Department is required.')
    .bail().isLength({ max: 120 }).withMessage('Department cannot exceed 120 characters.');

/**
 * A registration date records something that has already happened. The form
 * refuses a future date at the field, and the API enforces the same rule so the
 * product's own rule cannot be bypassed by anything that is not the form — a
 * record with a date that has not arrived yet would be nonsense on the register
 * (and would allocate a student ID for a year nobody is in).
 */
const isNotInTheFuture = (value) => {
  const date = value instanceof Date ? value : new Date(value);
  return !Number.isNaN(date.getTime()) && date.getTime() <= Date.now();
};

const dateOfRegistration = () =>
  body('dateOfRegistration').optional({ values: 'falsy' }).isISO8601()
    .withMessage('Date of registration must be a valid date.')
    .bail().custom(isNotInTheFuture)
    .withMessage('Date of registration cannot be in the future.')
    .toDate();

const enrollmentStatus = () =>
  body('enrollmentStatus').optional({ values: 'falsy' }).trim()
    .isIn(ENROLLMENT_STATUSES)
    .withMessage(`Status must be one of: ${ENROLLMENT_STATUSES.join(', ')}.`);

/**
 * An absolute URL or a site-relative path. An empty string is allowed on
 * purpose: that is how an administrator removes a student's photo.
 */
const avatarUrl = () =>
  body('avatarUrl').optional({ values: 'undefined' }).trim()
    .custom((value) => value === '' || /^(\/|https?:\/\/)\S*$/i.test(value))
    .withMessage('Profile photo must be a valid URL or a path starting with /.');

const optional = (rules) => rules.map((rule) => rule.optional({ values: 'undefined' }));

const mongoId = (field = 'id') =>
  param(field).trim().notEmpty().withMessage('A student id is required.')
    .bail().isMongoId().withMessage('That student id is not valid.');

/**
 * Student IDs and timestamps belong to the application. A client that sends
 * one gets an explicit error rather than having the value silently dropped.
 */
const rejectedFields = () => {
  const rules = STUDENT_PROTECTED_FIELDS.map((field) =>
    body(field).custom((value) => value === undefined || value === null).withMessage(
      (value, { path }) =>
        path === 'studentId'
          ? 'Student IDs are generated by CampusDesk and cannot be provided.'
          : `\`${path}\` is managed by CampusDesk and cannot be provided.`,
    ),
  );

  return rules;
};

/** PATCH with nothing to change is a client mistake, and worth reporting. */
const requireAtLeastOneField = () =>
  body().custom((value = {}) =>
    STUDENT_EDITABLE_FIELDS.some((field) => value[field] !== undefined),
  ).withMessage('Provide at least one field to update.');

export const studentIdParam = [mongoId()];

export const createStudentRules = [
  ...rejectedFields(),
  name(),
  email(),
  phone(),
  course(),
  year(),
  department(),
  dateOfRegistration(),
  enrollmentStatus(),
  avatarUrl(),
];

export const updateStudentRules = [
  mongoId(),
  requireAtLeastOneField(),
  ...rejectedFields(),
  ...optional([
    name(),
    email(),
    phone(),
    course(),
    year(),
    department(),
    dateOfRegistration(),
    enrollmentStatus(),
    avatarUrl(),
  ]),
];

/**
 * Every list parameter is one value.
 *
 * Express parses `?status=active&status=inactive` into an array. Left alone that
 * array either reaches MongoDB as a shape nobody intended (`{ status: [a, b] }`,
 * which silently matches nothing) or throws while being trimmed — which is a 500
 * for a URL anybody can write. Nothing in CampusDesk sends a parameter twice, so
 * a repeated one is refused with the same 422 as any other invalid value.
 */
const singleValue = (fields) =>
  fields.map((field) =>
    query(field)
      .custom((value) => value === undefined || typeof value === 'string')
      .withMessage(`Provide \`${field}\` once.`),
  );

/** Query rules for the search / filter / sort / pagination endpoint. */
export const listStudentRules = [
  ...singleValue([
    'search',
    'status',
    'year',
    'department',
    'course',
    'sort',
    'order',
    'page',
    'limit',
  ]),
  query('search').optional().trim().isLength({ max: MAX_SEARCH_LENGTH })
    .withMessage(`Search term must be ${MAX_SEARCH_LENGTH} characters or fewer.`),
  query('status').optional().trim().isIn(ENROLLMENT_STATUSES)
    .withMessage(`Status must be one of: ${ENROLLMENT_STATUSES.join(', ')}.`),
  query('year').optional().trim().isIn(STUDENT_YEARS)
    .withMessage(`Year must be one of: ${STUDENT_YEARS.join(', ')}.`),
  query('department').optional().trim().isLength({ max: 120 })
    .withMessage('Department filter is too long.'),
  query('course').optional().trim().isLength({ max: 120 })
    .withMessage('Course filter is too long.'),
  query('page').optional().isInt({ min: 1 }).withMessage('Page must be 1 or greater.').toInt(),
  query('limit').optional().isInt({ min: 1, max: MAX_PAGE_SIZE })
    .withMessage(`Limit must be between 1 and ${MAX_PAGE_SIZE}.`).toInt(),
  query('sort').optional().trim().isIn(STUDENT_SORT_FIELDS)
    .withMessage(`Sort must be one of: ${STUDENT_SORT_FIELDS.join(', ')}.`),
  query('order').optional().trim().toLowerCase().isIn(STUDENT_SORT_DIRECTIONS)
    .withMessage(`Order must be one of: ${STUDENT_SORT_DIRECTIONS.join(', ')}.`),
];
